FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ED

Service Oriented Architecture specified for the ED project.

#######################
# Group 01 - Profiles
#######################

Resources related to user's profile in the API.

## Profiles collections [/profiles{?orgType}{?searchType}{?searchValue}{?page}]

+ Attributes
    + profiles (array[ProfileResult1,ProfileResult2,ProfileResult3], required) - array of profiles
    + count: 3 (number, required) - total number of resources fetched by the query.

### List Profiles [GET]
Search user profiles.

+ Parameters
    + searchType: lname (enum[string]) - Field to filter
        + Members
            + lname
            + fname
            + email
            + dname
            + dcode
    + searchValue: BIANCHI (string) - value to search
    + orgType: UO (string) - Codice tipo struttura da filtrare
    + page: 1 (optional, number) - The page of profiles to return

+ Response 200 (application/json)

    + Attributes (Profiles collections)

+ Response 400
    Returned when input does not pass validation.
    
    + Body    
    
+ Response 404
    Returned when the required resource cannot be found.

    + Body
    
+ Response 500
    Returned when a generic error occours.

    + Body

## Profile [/profiles/{id}]

+ Parameters
    + id: 1 (required, number) - ID of the user

+ Attributes (ProfileDetail)

### Read Profile [GET]

+ Response 200 (application/json)

    + Attributes (Profile)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Profile [PUT]

+ Request (application/json)

    + Attributes (Profile Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Profile [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## User personal profile [/profiles/my]

Used to retrieve user personal details.

### Read Profile [GET]

+ Response 200 (application/json)
  + Attributes (Profile)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

#######################
# Group 02 - Search types
#######################

## Search types collections [/types]

+ Attributes (array)
  - Last name
  - First name
  - Email
  - Department name
  - Department code
  

### List types [GET]

+ Response 200 (application/json)
  + Attributes (Search types collections)


# Data Structures

## ProfileResult1 (object)
+ id: 1 (required, number) - ID of the profile
+ firstName: `MARIO` (required, string)
+ lastName: `BIANCHI` (required, string)
+ ou_code: `XL78481` (required, string)
+ ou_descr: `C-BOM` (required, string)
+ phone: `3901112345678` (string) - A string with the following format: `<2 digits country code>-<phone number>`
+ email: `mbianchi@acme.it` (required, string)
+ country: `Italy`
+ imageUrl: `http://url.of.image/image1.png`

## ProfileResult2 (object)
+ id: 2
+ firstName: `ROSA`
+ lastName: `BIANCHI`
+ ou_code: `XL78439`
+ ou_descr: `Service Management`
+ phone: `3901112345678` (string) - A string with the following format: `<country code, prefix, number>`
+ email: `rbianchi@acme.it`
+ country: `Austria`
+ imageUrl: `http://url.of.image/image2.png`

## ProfileResult3 (object)
+ id: 2
+ firstName: `PAOLO`
+ lastName: `BIANCHI`
+ ou_code `XJ99196`
+ ou_descr: `Open Special Support AT`
+ phone: `3901112345678` (string) - A string with the following format: `<country code, prefix, number>`
+ email: `pbianchi@acme.it`
+ country: `Germany`
+ imageUrl: `http://url.of.image/image3.png`

## Address (object)
- street: Via Nizza 15
- city: Torino
- country: Italy
- zip: 12345

## ProfileDetail (object)
+ id: 1 (required, number) - ID of the profile
+ firstName: `MARIO` (required, string)
+ lastName: `BIANCHI` (required, string)
+ ou_code: `XL78481` (required, string)
+ ou_descr: `C-BOM` (required, string)
+ email: `mbianchi@acme.it` (required, string)
+ profession: `Senior Developer` (required, string)
+ ismanager: `true`
+ phone (object)
    + country: 39
    + prefix: `011`
    + number: `12345678` (string)
+ mobilePhone (object)
    + country: `39`
    + prefix: `335`
    + number: `1234567` (string)
+ fax (object)
    + country: `39` (string)
    + prefix: `02` (string)
    + number: `3904912345678` (string)
+ address (Address)
+ imageUrl: `http://url.of.image/image.png`
+ businessUnit: `not used ?`,
+ internetAddress: `firstname.lastname@organization.com`
+ altInternetAddress: `firstname.lastname@organization2.com`
+ notesAddress: `????`
+ userId: `????`
+ businessAddress (Address)
+ expertiseSummary: `BLA BLA BLA` (string)
+ certifications: `BLA BLA BLA` (string)
+ experienceGeneral: `BLA BLA BLA` (string)
+ experienceIndustry: `BLA BLA BLA` (string)
+ technicalExperience: `BLA BLA BLA` (string)
+ solutionsProducts: `BLA BLA BLA` (string)
+ communities: `BLA BLA BLA` (string)
+ businessGoals: `BLA BLA BLA` (string)
+ professionalOrganizations: `BLA BLA BLA` (string)
+ projects: `BLA BLA BLA` (string)
+ team: `BLA BLA BLA` (string)
+ otherRoles: `????` (string)

## Profile Update (object)
+ Include Profile
+ image: `R0lGODlhEAAOALMAAOazToeHh0tLS/7LZv/0jvb29t/f3//Ub//ge8WSLf/rhf/3kdbW1mxsbP//mf///yH5BAAAAAAAL` (string) - serialized stream (base64) representing the image.